version: 2
jobs:
  default:
    docker:
      - image: openresty/openresty:1.13.6.2-2-centos
    steps:
      - checkout
      - run: yum -y install make
      - run: make install-test-deps-yum
      - run: make install-test-deps
      - run: make test
      - store_test_results:
          path: t/tmp/logs
  alpine:
    docker:
      - image: openresty/openresty:1.13.6.2-2-alpine-fat
    steps:
      - checkout
      - run: make install-test-deps-apk
      - run: make install-test-deps
      - run: make test
      - store_test_results:
          path: t/tmp/logs
  ubuntu:
    docker:
      - image: openresty/openresty:1.13.6.2-2-bionic
    steps:
      - checkout
      - run: make install-test-deps-apt
      - run: make install-test-deps
      - run: make test
      - store_test_results:
          path: t/tmp/logs
  # Test in older version before LUAJIT_ENABLE_LUA52COMPAT was enabled (to test
  # under LuaJIT's 5.1 mode).
  lua51:
    docker:
      - image: openresty/openresty:1.11.2.1-centos
    environment:
      PATH: /usr/local/openresty/luajit/bin:/usr/local/openresty/bin:/usr/local/openresty/nginx/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      TEST_NGINX_RESOLVER: 127.0.0.11 ipv6=off
    steps:
      - checkout
      - run: yum -y install make
      - run: make install-test-deps-yum
      - run: make install-test-deps
      - run: make test
      - store_test_results:
          path: t/tmp/logs
workflows:
  version: 2
  build:
    jobs:
      - default
      - alpine
      - ubuntu
      - lua51

  # Also run one job every night, just to ensure we catch any potential Let's
  # Encrypt API changes.
  nightly:
    triggers:
      - schedule:
          cron: "18 7 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - default
      - alpine
      - ubuntu
      - lua51
